import type {
  CameraDelegate,
  GoProHero11Capabilities,
  GoProHero11Mode,
} from "./types";

import { SetHero11Settings } from "./set-hero-11-settings";

export class Hero11Delegate implements CameraDelegate {
  public readonly capabilities: GoProHero11Capabilities = {
    modes: [
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "telephoto",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "telephoto",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "telephoto",
        levellingType: "smooth",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "telephoto",
        levellingType: "smooth",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "wide",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "wide",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "5.3k",
      },

      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "telephoto",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "telephoto",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "wide",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "wide",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "5.3k",
      },

      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "telephoto",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "wide",
        levellingType: "none",
        resolution: "5.3k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "5.3k",
      },

      {
        aspectRatio: "16:9",
        frameRate: 120,
        lens: "telephoto",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 100,
        lens: "telephoto",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 120,
        lens: "telephoto",
        levellingType: "smooth",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 100,
        lens: "telephoto",
        levellingType: "smooth",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 120,
        lens: "wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 100,
        lens: "wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 120,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 100,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "4k",
      },

      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "telephoto",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "telephoto",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "telephoto",
        levellingType: "smooth",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 60,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 50,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "4k",
      },

      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "telephoto",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "telephoto",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 30,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 25,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "4k",
      },

      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "telephoto",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "telephoto",
        levellingType: "lock",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "wide",
        levellingType: "none",
        resolution: "4k",
      },
      {
        aspectRatio: "16:9",
        frameRate: 24,
        lens: "ultra-wide",
        levellingType: "none",
        resolution: "4k",
      },
    ],
  };
  applySettings(mode: GoProHero11Mode) {
    return new SetHero11Settings(mode);
  }
  getCurrentSettings(): GoProHero11Mode {
    throw new Error("Method not implemented.");
  }
}
